### ISSUE TITLE
Specify which Logging Quota was exceeded.

### ISSUE THREAD

**Issue by marwansalem** [googleapis/java-logging#1129]
I am getting this exception :
`com.google.cloud.logging.LoggingException: io.grpc.StatusRuntimeException: RESOURCE_EXHAUSTED: Quota exceeded for quota metric 'Read requests' and limit 'Read requests per minute per user' of service 'logging.googleapis.com'`

It specifies that both `Read requests` and `Read requests per minute per user` metrics are exceeded. I am not sure which limit was exceeded upon reading the exception. However, when inspecting the logging quotas on https://console.cloud.google.com/apis/api/logging.googleapis.com/quotas?project=<project> , I find out that `Read Requests per minute` was never exceeded.

I'd love for the exception to be more specific.

Another thing, I could not find any documentation for the `Read requests per minute per user`  metric. I do not know what qualifies as a user, is it a service account? 

Thank you.

**Comment by meredithslota** [comment]
Hi @marwansalem — I got some additional info from our internal team. Generally speaking, the quota might be consumed by another project key, depending on which API key is used to call logging API. If you're able to file a support ticket (for sharing project details), the team can look into what's happening with your specific situation. https://cloud.google.com/support-hub

**Comment by meredithslota** [comment]
Following up here — I've gotten clarification from the internal team that `user` means individual user ID _or_ client IP address; individual user ID takes precedence over client IP address. I've filed a feature request for clarification of the error message too, since it appears that while the error message is stating that "Read requests per minute per user" was exceeded, in fact there is no quota called "Read requests" — that is the underlying metric from which all read quotas are drawn, so the limit that's being exceeded is the `Read requests per minute per user` (as you found when you checked the console). I agree it's confusingly phrased. Googlers, you can track this request here: b/278149992

**Comment by meredithslota** [comment]
Closing this specific issue as the feature request is for the service team and not for the library.
