### ISSUE TITLE
[Accessing LogEntries through the logging.v2 API] Why is the proto_payload not deserialized into a AuditLog object?

### ISSUE THREAD

**Issue by sten1ee** [googleapis/java-logging#269]
I have the following 2 questions:
Why is it that when accessing LogEntry(s) through the logging.v2 API, the LogEntry object has its proto_payload in a raw (serialized) form?
And what is the canonical way to get this proto_payload deserialized into an AuditLog object?

**Comment by Daniel-Sanche** [comment]
We recommend people to use the more friendly `logging` library, instead of the auto-generated `logging_v2`. You shouldn't have to worry about things like proto serializing to use the logging library. 

I know `logging` vs `logging_v2` is confusing, we plan on making things more clear in the next major release
