### ISSUE TITLE
Replace StringPayload with JsonPayload

### ISSUE THREAD

**Issue by dansiviter** [googleapis/java-logging#305]
**Is your feature request related to a problem? Please describe.**
As the log handler is using `StringPayload` more advanced functionality such as correctly linking `serviceContext` and `reportLocation` for Error Reporting and contextual information via structural formatting isn't possible.

**Describe the solution you'd like**
A way to both set and decorate a `com.google.cloud.logging.Payload.JsonPayload`.

**Describe alternatives you've considered**
Written my own implementation that does it.

**Additional context**
* https://cloud.google.com/logging/docs/structured-logging
* https://cloud.google.com/error-reporting/docs/formatting-error-messages

**Comment by minherz** [comment]
Thank you, @dansiviter . Are you referencing to the JUL [LogHandler](https://github.com/googleapis/java-logging/blob/4a3df8e98f5613b20a09f0f66eb74a71fea62cdf/google-cloud-logging/src/main/java/com/google/cloud/logging/LoggingHandler.java)? Indeed it does not publish Json. because [LogRecord](https://docs.oracle.com/javase/7/docs/api/java/util/logging/LogRecord.html) supports only the string payload.
Would you be interested to submit your implementation as a PR?

**Comment by minherz** [comment]
I close this issue due the lack of response. Feel free to re-open it if you have additional inputs.
